"""create votes table auto

Revision ID: b51352b6146c
Revises: b30f50c141fd
Create Date: 2024-03-14 17:20:03.614021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b51352b6146c'
down_revision: Union[str, None] = 'b30f50c141fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete="CASCADE"), nullable=False),
    sa.Column('post_id', sa.Integer(), sa.ForeignKey('posts.id', ondelete="CASCADE"), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - ###
    op.drop_table('votes')
